name: social_media
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  lottie: ^3.3.0
  go_router: ^14.6.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  logger: ^2.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  
  assets:
    - assets/animations/
  

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  
  
  
  
  
  
  
  
  
  
